
#include <float.h>
#include <limits.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

#include <f2c.h>

/* prototype generated by f2c */

extern int dn2gb_(integer *n, integer *p, doublereal *x, doublereal *b, S_fp calcr, S_fp calcj, 
  integer *iv, integer *liv, integer *lv, doublereal *v, integer *uiparm, doublereal *urparm, U_fp ufparm);
extern int divset_(integer *kind, integer *iv, integer *liv, integer *lv, doublereal *v);
  
int osb1j(integer *ptn, integer *ptp, doublereal *x, integer *ptnf, doublereal *j, integer *ptlty, doublereal *ty, U_fp ufparm) {
  int i, n = (int) *ptn, p = (int) *ptp, nf = (int) *ptnf, lty = (int) *ptlty;
  double ti;

  for (i=0; i<n; i++) {
     ti         = (double) ty[i];
     j[i      ] = (doublereal) (-1.0);
     j[i +   n] = (doublereal) (- exp(x[3]*ti));
     j[i + 2*n] = (doublereal) (- exp(x[4]*ti));
     j[i + 3*n] = (doublereal) (ti*x[1]*j[i+  n]);
     j[i + 4*n] = (doublereal) (ti*x[2]*j[i+2*n]);
  }
  
  return(0);
}

int osb1r(integer *ptn, integer *ptp, doublereal *x, integer *ptnf, doublereal *r, integer *ptlty, doublereal *ty, U_fp ufparm) {
  int i, n = (int) *ptn, p = (int) *ptp, nf = (int) *ptnf, lty = (int) *ptlty;
  double ti, yi;

  for (i=0; i<n; i++) {
     ti   = (double) ty[i];
     yi   = (double) ty[i+lty];
     r[i] = (doublereal) (yi - (x[0] + x[1]* exp(x[3]*ti) + x[2]* exp(x[4]*ti)));
  }
  
  return(0);
}

int dummy(void) { return(0);}

int main (int argc, char *argv[]) {

  int i;
  const int nParam =  5;
  const int nObser = 33;

  integer iv[82+4*nParam], ui[1];
  doublereal b[2*nParam], ty[2*nObser], v[105+nParam*(nObser+2*nParam+21)+2*nObser], x[nParam];
  integer liv = 82+4*nParam, lty = nObser, lv = 105+nParam*(nObser+2*nParam+21)+2*nObser, n = nObser, p = nParam, kind = 1;
  
  for (i=0; i<nObser; i++) ty[i] = -10.0 * ((double) i);

  ty[1+nObser-1]  = 8.44e-1; ty[2+nObser-1]  = 9.08e-1; ty[3+nObser-1]  = 9.32e-1;
  ty[4+nObser-1]  = 9.36e-1; ty[5+nObser-1]  = 9.25e-1; ty[6+nObser-1]  = 9.08e-1;
  ty[7+nObser-1]  = 8.81e-1; ty[8+nObser-1]  = 8.50e-1; ty[9+nObser-1]  = 8.18e-1;
  ty[10+nObser-1] = 7.84e-1; ty[11+nObser-1] = 7.51e-1; ty[12+nObser-1] = 7.18e-1;
  ty[13+nObser-1] = 6.85e-1; ty[14+nObser-1] = 6.58e-1; ty[15+nObser-1] = 6.28e-1;
  ty[16+nObser-1] = 6.03e-1; ty[17+nObser-1] = 5.80e-1; ty[18+nObser-1] = 5.58e-1;
  ty[19+nObser-1] = 5.38e-1; ty[20+nObser-1] = 5.22e-1; ty[21+nObser-1] = 5.06e-1;
  ty[22+nObser-1] = 4.90e-1; ty[23+nObser-1] = 4.78e-1; ty[24+nObser-1] = 4.67e-1;
  ty[25+nObser-1] = 4.57e-1; ty[26+nObser-1] = 4.48e-1; ty[27+nObser-1] = 4.38e-1;
  ty[28+nObser-1] = 4.31e-1; ty[29+nObser-1] = 4.24e-1; ty[30+nObser-1] = 4.20e-1;
  ty[31+nObser-1] = 4.14e-1; ty[32+nObser-1] = 4.11e-1; ty[33+nObser-1] = 4.06e-1;

  ui[0] = lty;
  (void) divset_(&kind, iv, &liv, &lv, v);

  x[0] =  0.50;
  x[1] =  1.50;
  x[2] = -1.00;
  x[3] =  0.01;
  x[4] =  0.02;

  b[0] = -DBL_MAX; b[1] = DBL_MAX;
  b[2] = -DBL_MAX; b[3] = DBL_MAX;
  b[4] = -DBL_MAX; b[5] = DBL_MAX;
  b[6] = -DBL_MAX; b[7] = 0.125;
  b[8] = 0.03;     b[9] = DBL_MAX;

  (void) dn2gb_(&n, &p, x, b, osb1r, osb1j, iv, &liv, &lv, v, ui, ty, dummy);
  
  printf("Return code generated by call to dn2gb: IV[0] = %d\n", iv[0]);
  
  exit(0);
}
