#include <float.h>
#include <limits.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

#include <f2c.h>

/* prototype generated by f2c */

extern int sa_(const integer *n, doublereal *x, integer *max, doublereal *rt, doublereal *eps,
  integer *ns, integer *nt, const integer *neps, integer *maxevl, doublereal *lb, doublereal *ub,
  doublereal *c,integer *iprint, integer *iseed1, integer *iseed2, doublereal *t,
  doublereal *vm, doublereal *xopt, doublereal *fopt, integer *nacc, integer *nfcnev,
  integer *nobds, integer *ier, doublereal *fstar, doublereal *xp, integer *nacp);

int fcn_(integer *n, doublereal *theta, doublereal*h) {
  double x = theta[0]/(theta[0]+theta[1]);
  *h = 8.3143*x*log(x) + 8.3143*(1.0-x)*log(1.0-x) + 20.0*x*(1.0-x) - (0.473932799*x - 1.055282429);
  return (0);
}

int main (int argc, char *argv[]) {
  const integer n = 2;
  const integer neps = 4;

  doublereal  lb[n], ub[n], x[n], xopt[n], c[n], vm[n], fstar[neps], xp[n], t, eps, rt, fopt;
  integer  nacp[n], ns, nt, nfcnev, ier, iseed1, iseed2, maxevl, iprint, nacc, nobds;
  integer max;
  int i;

  max = 0;
  eps = 1.0e-6;
  rt = 0.1; /* .5; */
  iseed1 = 1;
  iseed2 = 2;
  ns = 20;
  nt = 5;
  maxevl = 100000;
  iprint = 1;
  for (i=0; i<n; i++) {
    lb[i] = 0.0;
    ub[i] = 1.0;
    c[i]  = 2.0;
  }

  x[0] =  0.2;
  x[1] =  0.8;

  t = 5.0;
  for (i=0; i<n; i++) {
    vm[i] = 1.0;
  }

  printf("\nsimulated annealing example");
  printf("\nnumber of parameters: %d maximazation: %d", n, max);
  printf("\ninitial temp: %g rt: %g eps: %g", t, rt, eps);
  printf("\nns: %d nt: %d neps: %d", ns, nt, neps);
  printf("\nmaxevl: %d iprint: %d iseed1: %d", maxevl, iprint, iseed1);
  printf("\niseed2: %d", iseed1);

  printf("\nstarting values = %g,%g",x[0], x[1]);
  printf("\ninitial step length = %g,%g",vm[0], vm[1]);
  printf("\nlower bound = %g,%g",lb[0], lb[1]);
  printf("\nupper bound = %g,%g",ub[0], ub[1]);
  printf("\nc vector = %g,%g",c[0], c[1]);
  
  printf("\n   ****   end of driver routine output   ****");
  printf("\n   ****   before call to sa.             ****");      

  sa_(&n, x, &max, &rt, &eps, &ns, &nt, &neps, &maxevl, lb, ub, c, &iprint, &iseed1,
      &iseed2, &t, vm, xopt, &fopt, &nacc, &nfcnev, &nobds, &ier, fstar, xp, nacp);

  printf("\n   ****   results after sa   ****   ");     
  printf("\n   solution = %g,%g", xopt[0], xopt[1]);
  printf("\n   final step length = %g,%g", vm[0], vm[1]);

  printf("\noptimal function value: %g", fopt);
  printf("\nnumber of function evaluations: %d", nfcnev);
  printf("\nnumber of accepted evaluations: %d", nacc);
  printf("\nnumber of out of bound evaluations: %d", nobds);
  printf("\nfinal temp: %g  ier: %d", t, ier);
  
  printf("\n\nX = %g\n\n", xopt[0]/(xopt[0]+xopt[1]));

  exit(0);
}
