/* DO NOT MODIFY. AUTOGENERATED FROM /Users/ghiorso/Documents/ARCHIVE_CODE/xMelts/MELTS WS BxApp/Documentation.bxml */

#import <Cocoa/Cocoa.h>
#import <Bombaxtic/Bombaxtic.h>


@interface Documentation : BxHandler {

}

@end

@implementation Documentation

- (id)setup {
    [super setup];
;
    return self;
}

- (id)renderWithTransport:(BxTransport *)_ {
[super renderWithTransport:_];
    [_ write:@"<html>\n <body>\n  <a ref=\"http://thermofit.ofm-research.org/\">Web Service Documentation</a>\n </body>\n</html>\n"];
;
    return self;
}

@end

