  {"aegirine"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"aenigmatite"        ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"albite"             ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"akermanite"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"almandine"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"analcime"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"annite"             ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"anorthite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"apatite"            ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"betaquartz"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"chromite"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"cordierite"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"corundum"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"cristobalite"       ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"diopside"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"enthalpy"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"entropy"            ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"fayalite"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"ferropargasite"     ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"ferropseudobrookite",      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"fluorphlogopite"    ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"forsterite"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"gehlenite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"geikielite"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"grossular"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"grunerite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"hedenbergite"       ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"hematite"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"hercynite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"ilmenite"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"jadeite"            ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"kalsilite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"karrooite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"kdisilicate"        ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"kleucite"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"kmsilicate"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"larnite"            ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"liquid"             ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"magnesiohastingsite",      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"magnetite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"merwinite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"mgchromite"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"mgcummingtonite"    ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"mgspinel"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"monalbite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"monticellite"       ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"muscovite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"nadisilicate"       ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"naleucite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"namsilicate"        ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"nepheline"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"orthoenstatite"     ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"O2"                 ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"pargasite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"perovskite"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"periclase"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"phlogopite"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"protoenstatite"     ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"pseudobrookite"     ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"pseudowollastonite" ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"pyrope"             ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"pyrophanite"        ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"quartz"             ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"rutile"             ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"S2"                 ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"sanidine"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"sphene"             ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"tephroite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"tremolite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"tridymite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"ulvospinel"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"water"              ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"whitlockite"        ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"wollastonite"       ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"wustite"            ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"caperovskite-sx"    ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"cen-low-sx"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"cen-ht-sx"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"cen-hp-sx"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"pen-sx"             ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"coesite-sx"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"oen-sx"             ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"stishovite-sx"      ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"alloy-liquid"       ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"Fe-liquid"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"Ni-liquid"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"alloy-solid"        ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"Fe-metal"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"Ni-metal"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"amphibole"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"cummingtonite"      ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"grunerite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"tremolite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"biotite"            ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"annite"             ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"phlogopite"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"clinopyroxene"      ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"diopside"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"clinoenstatite"     ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"hedenbergite"       ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"alumino-buffonite"  ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"buffonite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"essenite"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"jadeite"            ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"cummingtonite"      ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"cummingtonite"      ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"grunerite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"feldspar"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"albite"             ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"anorthite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"sanidine"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"garnet"             ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"almandine"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"grossular"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"pyrope"             ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"hornblende"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"pargasite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"ferropargasite"     ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"magnesiohastingsite",      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"ilmenite ss"        ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"magnesioilmenite"   ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"ferroilmenite"      ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"kalsilite ss"       ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"na-nepheline"       ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"k-nepheline"        ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"vc-nepheline"       ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"ca-nepheline"       ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"leucite ss"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"leucite"            ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"analcime"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"na-leucite"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"majorite ss"        ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"grossular"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"pyrope"             ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"almandine"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"majorite"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"melilite"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"akermanite"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"gehlenite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"iron-akermanite"    ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"soda-melilite"      ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"nepheline ss"       ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"na-nepheline"       ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"k-nepheline"        ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"vc-nepheline"       ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"ca-nepheline"       ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"olivine"            ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"tephroite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"fayalite"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"co-olivine"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"ni-olivine"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"monticellite"       ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"forsterite"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"olivine-sx"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"forsterite-sx"      ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"fayalite-sx"        ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"ortho oxide"        ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"pseudobrookite"     ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"ferropseudobrookite",      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"karrooite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"orthopyroxene"      ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"diopside"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"clinoenstatite"     ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"hedenbergite"       ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"alumino-buffonite"  ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"buffonite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"essenite"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"jadeite"            ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"perovskite ss"      ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"magnesioperovskite" ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"ferroperovskite"    ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"rhm oxide"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"geikielite"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"hematite"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"ilmenite"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"pyrophanite"        ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"msg oxide"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"geikielite"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"hematite"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"ilmenite"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"pyrophanite"        ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"corundum"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"ringwoodite ss"     ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"magnesioringwoodite",      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"ferroringwoodite"   ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"spinel"             ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"chromite"           ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"hercynite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"magnetite"          ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"spinel"             ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"ulvospinel"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"wadsleyite ss"      ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"magnesiowadsleyite" ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"ferrowadsleyite"    ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"wustite ss"         ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid phase adjustment     */
  {"magnesiowustite"    ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
  {"ferrowustite"       ,      0.0,     0.0,     0.0, FALSE, FALSE, FALSE, FALSE }, /* Solid component adjustment */
